### ISSUE TITLE
Missing HeartBeats on Console Application

### ISSUE THREAD

**Issue by EmiliaVieira** [pootmhicnought/Delphi_AMQP#3]
Hi, I'm using these components, I created two applications in Delphi 10.3, a Form Application and a Console Application, in both applications, I do the same thing, I just open the AMQP connection and in the RabbitMQ Management, I monitor the sending of heartbeats.
The Form Application works correctly, but in the Console Application after a few minutes the connection is closed according to the log because of missed heartbeats from client.

My code is the same for the two applications:
_AMQP := TAMQPConnection.Create;
AMQP.MaxChannel    := 4;
AMQP.HeartbeatSecs := 60;
AMQP.Host          := '127.0.0.1';
AMQP.Port          := 5672;
AMQP.VirtualHost   := '/';
AMQP.Username      := 'guest';
AMQP.Password      := 'guest';
AMQP.Timeout := INFINITE;
AMQP.Connect;_

**Is there any component limitation for CONSOLE APPLICATION?**
The error in the log is:
2023-12-20 10:08:06.774000-03:00 [error] <0.5172.0> closing AMQP connection <0.5172.0> (127.0.0.1:61322 -> 127.0.0.1:5672):
2023-12-20 10:08:06.774000-03:00 [error] <0.5172.0> **missed heartbeats from client**, timeout: 60s

**Comment by ghost** [comment]
I haven't tried these components in a console application.  

Bear in mind that console applications are not threaded so there is no main VCL thread propagating messages .  I think you'll need to put the component in a thread and then your console application will need to repeat either sleep(1) or threadobject.processrequests (not sure offhand on the specific method in TThread).

I don't have an installation of delphi handy to try it out right now.  I might be able to take a shot as this later.

**Comment by EmiliaVieira** [comment]
Thanks for answering. I tried putting the component in a thread, but it still doesn't work. If you think of any other alternative, please let me know.

**Comment by ghost** [comment]
I just added a Console demo to the project, here's the PR if you want to get quick look:
https://github.com/pootmhicnought/Delphi_AMQP/pull/4

Or just checkout the branch. I think that'll get you started.  

I'm not sure if .waitfor is the best way to do the work however that allows all of the threads to get time and seems to function just fine.

**Comment by EmiliaVieira** [comment]
Thanks for answering, I ran the example, while there is traffic on the network the connection remains open, but if after the end of sending and receiving messages the application is kept open for a while, as there is no network traffic and the Console Application cannot send heartbeats, the error missed heartbeats from client keeps happening.
**I need the heartbeats to be sent in these moments of network idleness.**
To achieve this, I had to change the **AMQP.Connection**, I replaced the Timer(**FHeartbeatTimer**) that controls the heartbeats by a **Thread**, since Console Applications don't have a message pump.
I'm doing some more validations and as soon as I'm done I'll make the Pull Request from AMQP.Connection.

**Comment by ghost** [comment]
Good catch, and thanks for pitching in!

**Comment by ghost** [comment]
I merged the PR into main

**Comment by EmiliaVieira** [comment]
Solved by changing the timer by a thread at the AMQP.Connection.
